### ISSUE TITLE
helm-dash-installed-docsets is gone

### ISSUE THREAD

**Issue by thanhvg** [dash-docs-el/helm-dash#186]
What should I use instead? `dash-docs-installed-docsets`? 

I have no idea how these things work but my `Spacemacs` `dash`  layer uses `helm-dash-installed-docsets`

**Comment by areina** [comment]
Hello,

Yes, the new function is `dash-docs-installed-docsets`. However, I've noticed that we're missing the alias from `helm-dash-installed-docsets` to `dash-docs-installed-docsets` in order to ensure backwards compatibility. Thanks for pointing this out, I'll open a PR to fix it.

Sorry for the inconvenience, cheers.
